// Action types

export const GET_COLLECTIONS_REQUEST = 'GET_COLLECTIONS_REQUEST'
export const GET_COLLECTIONS_SUCCESS = 'GET_COLLECTIONS_SUCCESS'
export const GET_COLLECTIONS_FAILURE = 'GET_COLLECTIONS_FAILURE'

export const CREATE_COLLECTION_REQUEST = 'CREATE_COLLECTION_REQUEST'
export const CREATE_COLLECTION_SUCCESS = 'CREATE_COLLECTION_SUCCESS'
export const CREATE_COLLECTION_FAILURE = 'CREATE_COLLECTION_FAILURE'

export const GET_COLLECTION_REQUEST = 'GET_COLLECTION_REQUEST'
export const GET_COLLECTION_SUCCESS = 'GET_COLLECTION_SUCCESS'
export const GET_COLLECTION_FAILURE = 'GET_COLLECTION_FAILURE'

export const GET_COLLECTION_TEAMS_REQUEST = 'GET_COLLECTION_TEAMS_REQUEST'
export const GET_COLLECTION_TEAMS_SUCCESS = 'GET_COLLECTION_TEAMS_SUCCESS'
export const GET_COLLECTION_TEAMS_FAILURE = 'GET_COLLECTION_TEAMS_FAILURE'

export const UPDATE_COLLECTION_REQUEST = 'UPDATE_COLLECTION_REQUEST'
export const UPDATE_COLLECTION_SUCCESS = 'UPDATE_COLLECTION_SUCCESS'
export const UPDATE_COLLECTION_FAILURE = 'UPDATE_COLLECTION_FAILURE'

export const PATCH_COLLECTION_REQUEST = 'PATCH_COLLECTION_REQUEST'
export const PATCH_COLLECTION_SUCCESS = 'PATCH_COLLECTION_SUCCESS'
export const PATCH_COLLECTION_FAILURE = 'PATCH_COLLECTION_FAILURE'

export const DELETE_COLLECTION_REQUEST = 'DELETE_COLLECTION_REQUEST'
export const DELETE_COLLECTION_SUCCESS = 'DELETE_COLLECTION_SUCCESS'
export const DELETE_COLLECTION_FAILURE = 'DELETE_COLLECTION_FAILURE'

export const GET_FRAGMENTS_REQUEST = 'GET_FRAGMENTS_REQUEST'
export const GET_FRAGMENTS_SUCCESS = 'GET_FRAGMENTS_SUCCESS'
export const GET_FRAGMENTS_FAILURE = 'GET_FRAGMENTS_FAILURE'

export const CREATE_FRAGMENT_REQUEST = 'CREATE_FRAGMENT_REQUEST'
export const CREATE_FRAGMENT_SUCCESS = 'CREATE_FRAGMENT_SUCCESS'
export const CREATE_FRAGMENT_FAILURE = 'CREATE_FRAGMENT_FAILURE'

export const GET_FRAGMENT_REQUEST = 'GET_FRAGMENT_REQUEST'
export const GET_FRAGMENT_SUCCESS = 'GET_FRAGMENT_SUCCESS'
export const GET_FRAGMENT_FAILURE = 'GET_FRAGMENT_FAILURE'

export const UPDATE_FRAGMENT_REQUEST = 'UPDATE_FRAGMENT_REQUEST'
export const UPDATE_FRAGMENT_SUCCESS = 'UPDATE_FRAGMENT_SUCCESS'
export const UPDATE_FRAGMENT_FAILURE = 'UPDATE_FRAGMENT_FAILURE'

export const DELETE_FRAGMENT_REQUEST = 'DELETE_FRAGMENT_REQUEST'
export const DELETE_FRAGMENT_SUCCESS = 'DELETE_FRAGMENT_SUCCESS'
export const DELETE_FRAGMENT_FAILURE = 'DELETE_FRAGMENT_FAILURE'

export const GET_CURRENT_USER_REQUEST = 'GET_CURRENT_USER_REQUEST'
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS'
export const GET_CURRENT_USER_FAILURE = 'GET_CURRENT_USER_FAILURE'

export const GET_USER_REQUEST = 'GET_USER_REQUEST'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_FAILURE = 'GET_USER_FAILURE'

export const GET_USERS_REQUEST = 'GET_USERS_REQUEST'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE'

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE'

export const GET_TEAMS_REQUEST = 'GET_TEAMS_REQUEST'
export const GET_TEAMS_SUCCESS = 'GET_TEAMS_SUCCESS'
export const GET_TEAMS_FAILURE = 'GET_TEAMS_FAILURE'

export const CREATE_TEAM_REQUEST = 'CREATE_TEAM_REQUEST'
export const CREATE_TEAM_SUCCESS = 'CREATE_TEAM_SUCCESS'
export const CREATE_TEAM_FAILURE = 'CREATE_TEAM_FAILURE'

export const UPDATE_TEAM_REQUEST = 'UPDATE_TEAM_REQUEST'
export const UPDATE_TEAM_SUCCESS = 'UPDATE_TEAM_SUCCESS'
export const UPDATE_TEAM_FAILURE = 'UPDATE_TEAM_FAILURE'

export const DELETE_TEAM_REQUEST = 'DELETE_TEAM_REQUEST'
export const DELETE_TEAM_SUCCESS = 'DELETE_TEAM_SUCCESS'
export const DELETE_TEAM_FAILURE = 'DELETE_TEAM_FAILURE'

export const FILE_UPLOAD_REQUEST = 'FILE_UPLOAD_REQUEST'
export const FILE_UPLOAD_SUCCESS = 'FILE_UPLOAD_SUCCESS'
export const FILE_UPLOAD_FAILURE = 'FILE_UPLOAD_FAILURE'

export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE'
export const HYDRATE = 'HYDRATE'

// The following actions are implemented elsewhere in pubsweet components

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'
