// Action types

export const GET_COLLECTION_REQUEST = 'GET_COLLECTION_REQUEST'
export const GET_COLLECTION_SUCCESS = 'GET_COLLECTION_SUCCESS'
export const GET_COLLECTION_FAILURE = 'GET_COLLECTION_SUCCESS'

export const GET_FRAGMENTS_REQUEST = 'GET_FRAGMENTS_REQUEST'
export const GET_FRAGMENTS_SUCCESS = 'GET_FRAGMENTS_SUCCESS'
export const GET_FRAGMENTS_FAILURE = 'GET_FRAGMENTS_FAILURE'

export const CREATE_FRAGMENT_REQUEST = 'CREATE_FRAGMENT_REQUEST'
export const CREATE_FRAGMENT_SUCCESS = 'CREATE_FRAGMENT_SUCCESS'

export const UPDATE_FRAGMENT_REQUEST = 'UPDATE_FRAGMENT_REQUEST'
export const UPDATE_FRAGMENT_SUCCESS = 'UPDATE_FRAGMENT_SUCCESS'

export const DELETE_FRAGMENT_REQUEST = 'DELETE_FRAGMENT_REQUEST'
export const DELETE_FRAGMENT_SUCCESS = 'DELETE_FRAGMENT_SUCCESS'

export const GET_USER_REQUEST = 'GET_USER_REQUEST'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_FAILURE = 'GET_USER_FAILURE'

export const GET_USERS_REQUEST = 'GET_USERS_REQUEST'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE'

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'

export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE'
export const HYDRATE = 'HYDRATE'
