export const HTML_TO_EPUB_CONV_REQUEST = 'HTML_TO_EPUB_CONV_REQUEST'
export const HTML_TO_EPUB_CONV_SUCCESS = 'HTML_TO_EPUB_CONV_SUCCESS'
export const HTML_TO_EPUB_CONV_FAILURE = 'HTML_TO_EPUB_CONV_FAILURE'
