#!/bin/sh

TESTCMD=$1

export NODE_ENV=test

./test/helpers/setup.js

echo "running test command $TESTCMD"

$TESTCMD

if [ $? -eq 0 ]
then
  echo "test suite passed - cleaning up"
  ./test/helpers/cleanup.js
  exit 0
else
  echo "test suite failed - cleaning up"
  ./test/helpers/cleanup.js
  exit 1
fi
